'''
python -m mani_skill.examples.test_mplib --render-mode="human" --shader="rt-fast" -c "pd_joint_delta_pos" -e "PushCube-v1" -r "piper"
'''

import time
import random
import gymnasium as gym
import numpy as np
import sapien

import mplib 

from scipy.spatial.transform import Rotation

class ManiSkillPiperDemo:
    def __init__(self):
        # 1. 启动ManiSkill环境，获取scene和robot
        self.env = gym.make(
            "PushCube-v1",
            obs_mode="none",
            control_mode="pd_joint_delta_pos",
            render_mode="human",
            robot_uids="piper",
            sensor_configs=dict(shader_pack="rt-fast"),
            human_render_camera_configs=dict(shader_pack="rt-fast"),
            viewer_camera_configs=dict(shader_pack="rt-fast"),
            enable_shadow=True,
        )
        self.viewer = self.env
        obs, _ = self.env.reset(options=dict(reconfigure=True,robot_uids="piper",))
        self.scene = self.env.unwrapped.scene
        self.scene.set_timestep(1 / 240)
        self.load_robot() #加载机器人

        # 2. 初始化mplib Planner
        self.setup_planner()

        # 3. 设定初始关节
        init_qpos = np.zeros(self.robot.dof)
        self.robot.set_qpos(init_qpos)

        # 4. 添加桌子和物体（可选，或直接用环境自带物体）
        # 可以用 self.scene.create_actor_builder() 添加物体

    def load_robot(self, **kwargs):
        """
        This function loads a robot from a URDF file into the Sapien Scene.
        Note that does mean that setup_scene() must be called before this function.
        """
        self.robot = self.env.unwrapped.agent.robot
        
        # # 该设置会让机械臂位于桌子中央,而非桌子边缘
        # self.robot.set_root_pose(
        #     sapien.Pose(
        #         kwargs.get("robot_origin_xyz", [0, 0, 0]),
        #         kwargs.get("robot_origin_quat", [1, 0, 0, 0]),
        #     )
        # )

        # # 设置机械臂离物品更近一点，增加IK成功概率
        # # 无效，无论设什么参数都会导致机械臂位于正中央
        # self.robot.set_root_pose(
        #     sapien.Pose(
        #         kwargs.get("robot_origin_xyz", [-0.1, 0, 0]),
        #         kwargs.get("robot_origin_quat", [1, 0, 0, 0]),
        #     )
        # )

        self.active_joints = self.robot.get_active_joints()


    def setup_planner(self):
        link_names = [link.get_name() for link in self.robot.get_links()]
        joint_names = [joint.get_name() for joint in self.robot.get_active_joints()]
        # print("link个数:", len(link_names))
        # print("joint个数:", len(joint_names))
        self.planner = mplib.Planner(
            urdf="/home/robot/miniconda3/envs/piper/lib/python3.10/site-packages/mani_skill/assets/robots/piper/piper.urdf",
            srdf="/home/robot/miniconda3/envs/piper/lib/python3.10/site-packages/mani_skill/assets/robots/piper/piper.srdf",
            user_link_names=link_names,
            user_joint_names=joint_names,
            move_group="gripper_base",
            # joint_vel_limits=np.ones(7),  #panda共9个关节,这里设为7,忽略最后两个夹爪关节
            # joint_acc_limits=np.ones(7)
            joint_vel_limits=np.ones(6),
            joint_acc_limits=np.ones(6)
        )

    def follow_path(self, result, headless = False):
        """Helper function to follow a path generated by the planner"""
        # number of waypoints in the path
        n_step = result["position"].shape[0]
        # this makes sure the robot stays neutrally boyant instead of sagging
        # under gravity
        print(f"follow_path中得到的plan给出的总时间步数:{n_step} 总用时：{result['duration']}")

        for i in range(n_step):
            qf = self.robot.compute_passive_force(
                gravity=True, coriolis_and_centrifugal=True
            )
            self.robot.set_qf(qf)
            # set the joint positions and velocities for move group joints only.
            # The others are not the responsibility of the planner
            for j in range(len(self.planner.move_group_joint_indices)):
                self.active_joints[j].set_drive_target(result["position"][i][j])
                self.active_joints[j].set_drive_velocity_target(
                    result["velocity"][i][j]
                )
            # simulation step
            self.scene.step()
            # render every 4 simulation steps to make it faster 渲染环境
            if i % 4 == 0 and not headless:
                self.scene.update_render()
                self.viewer.render()
        
        cur_pose = self.robot.find_link_by_name('gripper_base').pose.raw_pose[0].tolist()
        print("运动结束，已到达点: [" + ", ".join(f"{x:.2f}" for x in cur_pose) + "]\n")

    def set_gripper(self, pos):
        """
        Helper function to activate gripper joints
        Args:
            pos: position of the gripper joint in real number
        """
        # The following two lines are particular to the panda robot
        for joint in self.active_joints[-2:]:
            joint.set_drive_target(pos)
        # 100 steps is plenty to reach the target position
        for i in range(100):
            qf = self.robot.compute_passive_force(
                gravity=True, coriolis_and_centrifugal=True
            )
            self.robot.set_qf(qf)
            self.scene.step()
            if i % 4 == 0:
                self.scene.update_render()
                self.viewer.render()

    def move_to_pose(self, pose, with_screw=True, headless=False):
        world_pose = self.robot_to_world(pose , self.robot.get_root_pose().raw_pose[0].tolist())
        print("\n开始规划，目标点: [" + ", ".join(f"{x:.2f}" for x in world_pose) + "]")
        if with_screw:
            return self.move_to_pose_with_screw(pose, headless)
        else:
            return self.move_to_pose_with_RRTConnect(pose, headless)



    def move_to_pose_with_retry(self, pose, with_screw=True, max_retries=5, headless=False):
        """
        尝试移动到目标位姿，失败时在邻域内随机扰动重试
        """
        # 初始尝试
        result = self.move_to_pose(pose, with_screw)
        if result == 0:
            return 0  # 初始尝试成功
        
        # 重试机制
        original_pose = np.array(pose)  # 转换为numpy数组便于处理
        pos = original_pose[:3]         # 位置向量 [x, y, z]
        quat = original_pose[3:]        # 四元数 [qx, qy, qz, qw]

        for attempt in range(max_retries):
            print(f"\n第 {attempt+1} 次重试，原始目标: {[f'{x:.3f}' for x in original_pose]}")
            
            # ===== 位置扰动 =====
            new_pos = pos + np.random.uniform(-0.01, 0.01, size=3)
            
            # ===== 基于四元数的姿态扰动=====
            # 创建原始旋转对象
            orig_rot = Rotation.from_quat(quat)
            
            # 生成随机扰动旋转（小角度）
            random_axis = np.random.randn(3)  # 随机轴
            random_axis /= np.linalg.norm(random_axis)  # 归一化
            random_angle = np.random.uniform(-0.5, 0.5)  # 随机角度（度）
            
            # 创建扰动旋转对象
            perturb_rot = Rotation.from_rotvec(random_angle * np.pi/180 * random_axis)
            
            # 应用扰动：新旋转 = 扰动旋转 × 原始旋转
            new_rot = perturb_rot * orig_rot
            new_quat = new_rot.as_quat()  # [qx, qy, qz, qw]
            
            # 组合新位姿
            new_pose = np.concatenate([new_pos, new_quat]).tolist()
            
            # 尝试新位姿
            result = self.move_to_pose(new_pose, with_screw)
            if result == 0:
                return 0  # 重试成功
        
        # 所有重试均失败
        print(f"\n⚠️ 警告: 经过 {max_retries} 次重试仍失败")
        return result


    def move_to_pose_with_RRTConnect(self, pose, headless=False):
        print("使用RRTConnect motion规划")
        # result = self.planner.plan_pose(pose, self.robot.get_qpos(), time_step=1 / 250) #这里需修改，否则报错planner.py", line 177, assert len(qpos) == len(self.joint_limits), ( AssertionError: length of qpos (1) != number of total joints (8)
        result = self.planner.plan_pose(mplib.Pose(pose[:3], pose[3:]), self.robot.get_qpos()[0].numpy().squeeze(), time_step=1 / 140) #获取机械臂关节角度 转为numpy数组并展平 根源在于piper这套框架的get_qpos获取到二维数组，可拓展至多机械臂，而源代码期望的是一维数组
        # print(result)
        # plan_pose ankor end
        if result["status"] != "Success":
            print("RRTConnect规划失败",result["status"], "\n")
            return -1
        # do nothing if the planning fails; follow the path if the planning succeeds
        self.follow_path(result, headless)
        return 0
    

    def move_to_pose_with_screw(self, pose, headless=False):
        result = self.planner.plan_screw(
            mplib.Pose(pose[:3], pose[3:]),
            # self.robot.get_qpos(),    #这里需修改，否则报错planner.py", line 720 中 current_qpos = self.pad_move_group_qpos(current_qpos.copy()) AttributeError: 'Tensor' object has no attribute 'copy‘
            self.robot.get_qpos()[0].numpy().squeeze(),  #获取机械臂关节角度 转为numpy数组并展平 根源在于piper这套框架的get_qpos获取到二维数组，可拓展至多机械臂，而源代码期望的是一维数组
            time_step=1 / 140,
        )
        if result["status"] == "Success":
            print("使用screw motion规划")
            self.follow_path(result, headless)
            return 0
        else:
            # fall back to RRTConnect if the screw motion fails (say contains collision)
            print("screw motion规划失败，回退到RRTConnect规划")
            return self.move_to_pose_with_RRTConnect(pose, headless)

    def open_gripper(self):
        self.active_joints[-2].set_drive_target(0.4)    #joint7
        self.active_joints[-1].set_drive_target(-0.4)    #joint8
        for i in range(100): 
            qf = self.robot.compute_passive_force(
                gravity=True, 
                coriolis_and_centrifugal=True)
            self.robot.set_qf(qf)
            self.scene.step()
            if i % 4 == 0:
                self.scene.update_render()
                self.viewer.render()
        print("已打开夹爪\n")

    def close_gripper(self):
        for joint in self.active_joints[-2:]:
            joint.set_drive_target(0)
        for i in range(100):  
            qf = self.robot.compute_passive_force(
                gravity=True, 
                coriolis_and_centrifugal=True)
            self.robot.set_qf(qf)
            self.scene.step()
            if i % 4 == 0:
                self.scene.update_render()
                self.viewer.render()    
        print("已关闭夹爪\n")

    def robot_to_world(self, local_pose: list, root_pose: list):
        """
        机器人坐标系 -> 世界坐标系
        local_pose: [x, y, z, w, qx, qy, qz] (wxyz)
        root_pose:  [x, y, z, w, qx, qy, qz] (wxyz)
        返回: [x, y, z, w, qx, qy, qz] (wxyz)
        """
        # 1. 位置
        world_pos = (np.array(local_pose[:3]) + np.array(root_pose[:3])).tolist()

        # 2. 姿态
        # wxyz → xyzw
        q_local = [local_pose[4], local_pose[5], local_pose[6], local_pose[3]]
        q_root  = [root_pose[4],  root_pose[5],  root_pose[6],  root_pose[3]]

        r_local = Rotation.from_quat(q_local)
        r_root  = Rotation.from_quat(q_root)
        r_world = r_root * r_local          # 世界姿态 = 根姿态 ⊕ 局部姿态
        q_world_xyzw = r_world.as_quat()
        q_world_wxyz = [q_world_xyzw[3], q_world_xyzw[0], q_world_xyzw[1], q_world_xyzw[2]] #返回wxyz

        return world_pos + q_world_wxyz

    def world_to_robot(self, world_pose: list, root_pose: list):
        """
        世界坐标系 -> 机器人坐标系
        world_pose: [x, y, z, w, qx, qy, qz] (wxyz)
        root_pose:  [x, y, z, w, qx, qy, qz] (wxyz)
        返回: [x, y, z, w, qx, qy, qz] (wxyz)
        """  
        # 位置部分 减去基坐标
        # print("world_pose:", world_pose)  
        # print("root_pose:", root_pose)    
        local_pos = (np.array(world_pose[:3]) - np.array(root_pose[:3])).tolist() 
        # print("local_pos:", local_pos)  # [0.671142472, -5.62630369e-08, 0.213193089]

        # 姿态转换（使用四元数乘法）
        from scipy.spatial.transform import Rotation
        r_world = Rotation.from_quat([world_pose[4], world_pose[5], world_pose[6], world_pose[3]])  # xyzw
        r_root = Rotation.from_quat([root_pose[4], root_pose[5], root_pose[6], root_pose[3]])  # xyzw
        r_local = r_root.inv() * r_world
        local_quat_xyzw = r_local.as_quat()
        local_quat_wxyz = [local_quat_xyzw[3], local_quat_xyzw[0], local_quat_xyzw[1], local_quat_xyzw[2]]

        return local_pos + local_quat_wxyz  #拼接这两个list对象

    def demo(self, with_screw = True):
        root_pose = self.robot.get_root_pose().raw_pose[0].tolist() #基座位姿
        # print(f"基座位姿：{root_pose}")

        print(f"末端执行器初始位姿(wxyz)：{self.robot.find_link_by_name('gripper_base').pose.raw_pose[0].tolist()}") #[0.737256, 2.5551e-06, 0.675613, -5.0007e-06]

        cube_pose = self.env.get_wrapper_attr('obj').pose.raw_pose[0].tolist()  #或 self.env.unwrapped.obj.scene.actors['cube'].pose.raw_pose[0].tolist()
        print(f"物品坐标位于：{cube_pose[:3]}\n")

        cube_pos_top = cube_pose[:3].copy()
        cube_pos_top[2] += 0.16
        pose1_world = cube_pos_top + [0, 0, 1, 0]  
        pose1_robot = self.world_to_robot(pose1_world, root_pose) #转换到机械臂坐标系

        pos = pose1_robot[:3]
        qual = pose1_robot[3:]
        pose_1 = pos + qual  
        print("尝试到达物块上方")
        move_result = self.move_to_pose(pose_1, with_screw) #到达物块上方
        self.open_gripper()

        pos[2] -= 0.08
        pose_2 = pos + qual  
        print("尝试下放夹爪到物块位置")
        move_result = self.move_to_pose(pose_2, with_screw) #向下到到达物块位置
        self.close_gripper()

        pos[2] += 0.12
        pose_3 = pos + qual  
        print("尝试提起物块")
        move_result = self.move_to_pose(pose_3, with_screw) #提起

        pos[0] -= 0.2
        pose_4 = pos + qual  
        print("尝试收回夹爪")
        move_result = self.move_to_pose(pose_4, with_screw) #收回

        pos[2] -= 0.08
        pose_5 = pos + qual  
        print("尝试放下物块")
        move_result = self.move_to_pose(pose_5, with_screw) #放下
        self.open_gripper()

        pos[2] += 0.08
        pose_6 = pos + qual  
        print("尝试抬起夹爪")
        move_result = self.move_to_pose(pose_6, with_screw) #提起

    def test_MP_SR(self, num_tests=10000):
        # 对Screw和RRTConnect方法分别进行测试
        test_cases = [
            {"method": "Screw", "with_screw": True},
            {"method": "RRTConnect", "with_screw": False}
        ]
        
        results = {}
        
        for case in test_cases:
            method_name = case["method"]
            success_count = 0
            
            print(f"\n开始测试 {method_name} 方法 ({num_tests}次)...")
            
            for i in range(num_tests):
                # 重置环境以确保每次测试独立
                self.env.reset()
                
                # 获取当前环境的最新状态
                root_pose = self.robot.get_root_pose().raw_pose[0].tolist()
                cube_pose = self.env.get_wrapper_attr('obj').pose.raw_pose[0].tolist()
                
                # 计算目标位姿（物块上方）
                cube_pos_top = cube_pose[:3].copy()
                cube_pos_top[2] += 0.16
                pose1_world = cube_pos_top + [0, 0, 1, 0]  # 四元数表示
                pose1_robot = self.world_to_robot(pose1_world, root_pose)
                
                # 执行移动
                result = self.move_to_pose(pose1_robot, with_screw=case["with_screw"], headless=True)
                
                # 记录结果
                if result == 0:
                    success_count += 1
                
                if (i + 1) % max(1, num_tests//100) == 0:  # 根据测试次数自动调整报告频率
                    print(f"进度: {i+1}/{num_tests} | 成功率: {success_count/(i+1):.2%}")
            
            # 存储最终结果
            results[method_name] = {
                "success": success_count,
                "failure": num_tests - success_count,
                "success_rate": success_count / num_tests
            }
        
        # 打印最终统计结果
        print("\n" + "="*50)
        print("运动规划方法成功率统计:")
        print("="*50)
        
        for method, data in results.items():
            print(f"{method}方法:")
            print(f"  成功次数: {data['success']}/{num_tests}")
            print(f"  失败次数: {data['failure']}/{num_tests}")
            print(f"  成功率: {data['success_rate']:.4f} ({data['success_rate']:.2%})")
            print("-"*50)
        
        return results

    def plot_reachable_space(self, num_samples=1000, max_retries=3, with_screw=True):
        """
        通过蒙特卡洛采样绘制固定姿态下的可达空间三维图
        Args:
            num_samples: 采样点数量
            max_retries: 每个点的最大重试次数
            with_screw: 是否使用screw motion规划
        """
        import matplotlib.pyplot as plt
        from mpl_toolkits.mplot3d import Axes3D      
        
        # 获取机器人基座位姿
        root_pose = self.robot.get_root_pose().raw_pose[0].tolist()
        
        # 定义采样范围（TODO：根据机器人工作空间调整，在仿真器中调整姿态，找到大致边界）
        x_range = [-0.258, 0.09]    # x方向范围
        y_range = [-0.285, 0.285]   # y方向范围
        z_range = [0.136, 0.283]     # z方向范围
        
        # 存储采样结果
        reachable_points = []
        unreachable_points = []
        
        # 固定姿态（四元数 wxyz 格式）
        fixed_quat = [0, 0, 1, 0]  # 对应绕Y轴旋转180度
        
        print(f"开始可达空间采样，共{num_samples}个点...")
        start_time = time.time()
        
        for i in range(num_samples):
            # 随机采样一个位置
            pos = [
                random.uniform(x_range[0], x_range[1]),
                random.uniform(y_range[0], y_range[1]),
                random.uniform(z_range[0], z_range[1])
            ]
            
            # 构建目标位姿（位置+固定姿态）
            target_pose = pos + fixed_quat
            target_pose_robot = self.world_to_robot(target_pose, root_pose)
            
            # 尝试规划到这个位姿
            result = self.move_to_pose(
                target_pose_robot, 
                with_screw=with_screw, 
                headless=True
            )
            # print(f"result为：{result}")
            
            # 记录结果
            if result == 0:
                reachable_points.append(pos)
            else:
                unreachable_points.append(pos)
            
            # 重置机器人到初始位置
            self.robot.set_qpos(np.zeros(self.robot.dof))
            # 物理模拟几步确保稳定
            for _ in range(10):
                self.scene.step()
            
            # 打印进度
            if (i + 1) % max(1, num_samples // 10) == 0:
                elapsed = time.time() - start_time
                rate = (i + 1) / elapsed if elapsed > 0 else 0
                print(f"进度: {i+1}/{num_samples} | "
                      f"可达点: {len(reachable_points)} | "
                      f"不可达点: {len(unreachable_points)} | "
                      f"速度: {rate:.1f} 点/秒")
        
        # ---------- 1. 可达区域3D图 ----------
        plt.rcParams['font.family'] = ['WenQuanYi Zen Hei']   # Linux 设定中文字体 sudo apt-get install ttf-wqy-zenhei
        fig = plt.figure(figsize=(12, 10))
        ax = fig.add_subplot(111, projection='3d')
        
        # 绘制可达点（绿色）
        if reachable_points:
            rp = np.array(reachable_points)
            ax.scatter(rp[:, 0], rp[:, 1], rp[:, 2], 
                      c='g', marker='o', alpha=0.6, label='可达')
        
        # # 绘制不可达点（红色）
        # if unreachable_points:
        #     up = np.array(unreachable_points)
        #     ax.scatter(up[:, 0], up[:, 1], up[:, 2], 
        #               c='r', marker='x', alpha=0.3, label='不可达')
        
        # 设置坐标轴标签
        ax.set_xlabel('X轴')
        ax.set_ylabel('Y轴')
        ax.set_zlabel('Z轴')
        ax.set_title(f'固定姿态下的可达空间（姿态: [0,0,1,0]）\n采样点: {num_samples} | 可达率: {len(reachable_points)/num_samples:.2%}')
        
        # 设置视角
        ax.view_init(elev=30, azim=45)
        
        # 添加图例和网格
        ax.legend()
        ax.grid(True)
        
        # 添加机器人基座标记
        base_pos = root_pose[:3]
        ax.scatter(base_pos[0], base_pos[1], base_pos[2], 
                  c='b', marker='*', s=100, label='机器人基座')

        print(f"采样完成！可达点: {len(reachable_points)} | 不可达点: {len(unreachable_points)}") 
        if reachable_points:
            rp = np.array(reachable_points)
            print("可行 xyz 范围：")
            print(f"  x ∈ [{rp[:,0].min():.3f}, {rp[:,0].max():.3f}]")
            print(f"  y ∈ [{rp[:,1].min():.3f}, {rp[:,1].max():.3f}]")
            print(f"  z ∈ [{rp[:,2].min():.3f}, {rp[:,2].max():.3f}]")

        #显示可达区域采样结果3D图
        plt.tight_layout()
        plt.show()

        # ---------- 2. 二维投影直方图 ----------
        fig2, axes = plt.subplots(1, 3, figsize=(15, 4))
        proj = [(0, 1, 'XY'), (0, 2, 'XZ'), (1, 2, 'YZ')]
        for ax, (i, j, name) in zip(axes, proj):
            if reachable_points:
                ax.hist2d(rp[:, i], rp[:, j], bins=50, cmap='Greens')
                ax.set_xlabel(f'{name[0]} (m)')
                ax.set_ylabel(f'{name[1]} (m)')
                ax.set_title(f'{name} 平面投影')
            ax.set_aspect('equal', adjustable='box')
        plt.tight_layout()
        plt.show(block=False)

        # ---------- 3. 3D 凸包切片（可选）----------
        # 需要 convex-hull，pip install scipy
        from scipy.spatial import ConvexHull
        if reachable_points and len(reachable_points) >= 4:
            hull = ConvexHull(rp)
            fig3 = plt.figure(figsize=(8, 8))
            ax3 = fig3.add_subplot(111, projection='3d')
            # 绘制凸包面片
            for simplex in hull.simplices:
                ax3.plot_trisurf(rp[simplex, 0], rp[simplex, 1], rp[simplex, 2],
                                alpha=0.25, color='g')
            ax3.scatter(rp[:, 0], rp[:, 1], rp[:, 2], s=1, c='g')
            ax3.set_xlabel('X'); ax3.set_ylabel('Y'); ax3.set_zlabel('Z')
            ax3.set_title('可行域凸包')
            plt.show()
                

            return reachable_points, unreachable_points

if __name__ == "__main__":
    demo = ManiSkillPiperDemo()
    demo.demo()   #执行自动抓取demo #[0.01, 0.07, 0.19, 0.01, -0.00, 1.00, 0.00] [-0.19, 0.07, 0.22, 0.00, 0.00, 1.00, 0.00]
    # demo.test_MP_SR()   #统计mplib motion planning成功率
    # reachable, unreachable = demo.plot_reachable_space(num_samples=1000) # 蒙特卡洛采样分析可达空间（采样1000个点）